# .cpanel.yml

deployment:
  tasks:
    - export DEPLOY_ENV="production"
    # Create a virtual environment if it doesn't exist
    - if [ ! -d "venv" ]; then python3 -m venv venv; fi

    # Activate the virtual environment
    - source venv/bin/activate

    # Install dependencies
    - pip install -r requirements.txt

    # Run the bot (assuming bot.py is the entry point)
    - nohup python3 bot.py &

# Specify the directory containing the bot script
source:
  local: ./
  destination: /home/biruklir/Inline_Dictionary_Bot
